name: wildfire-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==22.3.1
  - python=3.7.5
  - pip:
    - ./whl_package/Fiona-1.8.6-cp37-cp37m-win_amd64.whl
    - ./whl_package/GDAL-2.4.1-cp37-cp37m-win_amd64.whl
    - ./whl_package/pyproj-1.9.6-cp37-cp37m-win_amd64.whl
    - ./whl_package/Shapely-1.6.4.post2-cp37-cp37m-win_amd64.whl
    - shapely==1.6.4.post2 
    - fiona==1.8.6 
    - pyproj==1.9.6 
    - pandas==0.25.2
    - pillow==6.2.0
    - descartes==1.1.0
    - matplotlib==3.1.1
    - numpy==1.17.3
    - geopandas==0.6.1
  

