name: wildfire-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==22.3.1
  - python==3.8.16

  - pip:
    - pandas==0.25.2
    - pillow==6.2.0
    - geopandas==0.6.1
    - descartes==1.1.0
    - matplotlib==3.1.1
    - numpy==1.17.3
    - shapely==1.6.4.post2
    - fiona==1.8.6
    - pyproj==1.9.6
    - ipykernel==6.20.2
    - autopep8==2.0.0
    - notebook==6.5.2
    - pre-commit==2.21.0
    - flake8==5.0.4
    - isort==5.11.4
    - build==0.10.0
    - twine==4.0.2
    - artifacts-keyring==0.3.2
    - pytest==7.2.2
    - plotly==5.14.1
    - jupytext==1.14.5
    - -r requirements.txt

